name: Tests and Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio httpx pytest-cov
        pip install -r requirements.txt
    - name: Create test database
      run: |
        python -c "from database import create_db_and_tables; create_db_and_tables()"
    - name: Run tests
      run: pytest
    - name: Delete test database
      run: |
        rm -f code_hints.db

  coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio httpx pytest-cov
        pip install -r requirements.txt
    - name: Create test database
      run: |
        python -c "from database import create_db_and_tables; create_db_and_tables()"
    - name: Generate coverage report
      run: pytest --cov=. --cov-report=xml
    - name: Delete test database
      run: |
        rm -f code_hints.db
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODE_COV_TOKEN }}
        slug: SanjinDedic/code_hint